from enum import StrEnum


class Code(StrEnum):
    """SUCCESS"""

    PROCESS_SUCCESS_CODE = "DB_0004"
    PROCESS_EXECUTED_SUCCESSFULLY = "DB_4001"
    PROVIDER_NAME_NO_EXIST = "DB_4002"
    CREATE_PROVIDER_GROUPS = "DB_4003"
    CREATE_PROVIDER_GROUPS_CONTRACTS = "DB_4004"
    CREATE_PROVIDER_GROUP = "DB_4005"
    DELETE_PROVIDER_GROUPS_CONTRACTS = "DB_4006"
    UPDATE_PROVIDER_GROUPS_CONTRACTS = "DB_4007"
    CHANGE_PROVIDER_STATUS = "DB_4008"
    CREATE_PROVIDER_GROUP_CONTRACT = "DB_4024"

    CICLE_CREATE = "DB_4009"
    PROCESING_NEW_CYCLE = "DB_4010"
    UPDATE_COMPENSATION_HEADER_OPEN = "DB_4011"
    RESUBMIT_COMPENSATION_HEADER = "DB_4012"
    CHANGE_OVERWRITTE = "DB_4014"
    UPDATE_COMPENSATION_HEADER = "DB_4017"
    SETTINGS_SAVED_SUCCESSFULLY = "DB_4022"
    DEDUCTIONS_SAVED = "DB_4026"

    """ WARNINGS """
    DEFAULT_WARNING = "DB_WARNING_4000"
    DEDUCTIONS_EXIST = "DB_WARNING_4014"
    CONTRACT_DATES_ALREADY_EXISTS = "DB_WARNING_4006"
    PROVIDER_GORUP_NAME_ALREADY_EXISTS = "DB_WARNING_4005"
    DETAIL_ALREADY_EXISTS = "DB_WARNING_4004"
    NAME_IS_USED_FOR_OTHER_GROUP = "DB_WARNING_4003"
    PROBLEM_SAVING_PROVIDERS = "DB_WARNING_4002"
    PROVIDER_NAME_EXIST = "DB_WARNING_4001"
    CONTRACT_NAME_ALREADY_EXISTS = "DB_WARNING_4013"

    """ ERRORS """
    DEFAULT_ERROR_CODE = "DB_ERROR_4000"
    DATA_NO_FOUND_IN_REQUEST = "DB_ERROR_4001"

    CREATE_MASTER_CATALOG_CODE = "DB_1022"
    UPDATE_MASTER_CATALOG_CODE = "DB_1023"
    DELETE_DETAIL_CATALOG_CODE = "DB_1024"
    DELETE_MASTER_CATALOG_CODE = "DB_1025"

    UPDATE_CONTRACT_STATUS_MAX_CONTRACTS_CODE = "DB_ERROR_4002"
    UPDATE_CONTRACT_STATUS_MAX_CONTRACTS_MSG = (
        "Groups can only have 1 active contracts of each type."
    )
