from enum import StrEnum


class Secrets(StrEnum):

    AES_KEY_AUTH = "AES-KEY-AUTH"
    AES_KEY_USER = "AES-KEY-USER"
    SECRET_RSA_KEY_2 = "SECRET-KEY-2"

    AUTH_JWT_USER_KEY = "AUTH-JWT-USER-KEY"
    AUTH_JWT_SECRET_KEY = "AUTH-JWT-SECRET-KEY"

    AZURE_SERVICE_BUS_NAMESPACE = "AZURE-SERVICE-BUS-NAMESPACE"
    AZURE_STORAGE_BLOB_URL = "AZURE-STORAGE-BLOB-URL"
    AZURE_BLOB_STORAGE_ACCOUNT_URL = "AZURE-BLOB-STORAGE-ACCOUNT-URL"
    AZURE_BLOB_STORAGE_CONTAINER_NAME = "AZURE-BLOB-STORAGE-CONTAINER-NAME"

    SECURITY_GRPC_ENDPOINT = "SECURITY-GRPC-HOST"
